### PR TITLE
Replace itsdangerous with authlib for JWS

### PR DESCRIPTION
**Pull request by mbillow**
@svintit - I broke this into a new MR based on @bensta's original branch, since I obviously can't contribute directly to his branch. This PR is his original commit with your feedback applied. Hopefully this carries the changes across the finish line. 😄 

**Note:** I also fixed a relative import statement in the tests and updated the dependencies to their latest minor versions.

### CODE REVIEW

**Comment by zbhuiyan** [comment]
@svintit is this ready to be merged? Thanks

**Comment by svintit** [comment]
@mbillow @zbhuiyan Apologies, i've been away on a work trip and was catching up on some other work. Will review now.

**Comment by svintit** [comment]
This looks good to me, nice work! I'll work on a deploying a new version now and will update here once it's done.

**Comment by svintit** [comment]
@mbillow @zbhuiyan All done, `1.4.5` is released - https://pypi.org/project/flask-oidc-ext/.

Had some issues with Travis CI, so moved away from it.

**Pull request merged**
