### PR TITLE
Add additional token and cache helper functions

### PR DESCRIPTION
**Pull request by aaronjolson**
Make get_token a method outside of the accept decorator. Add a couple methods for clearing individual tokens from the store of cached tokens for finer grained control.

Having functions to remove specific keys from the token caches is useful. It allows us to perform token validation multiple times (using different parameters based on scopes) on the same token, while being able to keep the cache from getting poisoned.
Without these changes, the only way to do that is to completely purge the cache in cases where we just want to remove a single token.

The get_token method is useful to be able to get the token from the request.
- validate a token/request outside of the decorator
- use that token for cache cleaning
The current workaround for this is to have the code for pulling the token off the request copied/duplicated client side.

### CODE REVIEW

**Comment by svintit** [comment]
Hey @aaronjolson, the PR seems fine, just trying to understand how useful/necessary this is. Please provide some use cases; ideally for situations in which you cannot easily code around this in your own codebase for wherever the package is being used.

**Comment by aaronjolson** [comment]
@svintit - I updated the description. Is that helpful?

**Comment by svintit** [comment]
Thanks @aaronjolson makes sense. Typically I wouldn't merge changes that can be controlled "client_side" as it's not a necessity and I don't have the time typically to continuously release these sorts of updates. 

Nonetheless, I'll have this merged and released as I do believe it's useful. 

I'll update you once this is released.

**Comment by svintit** [comment]
@aaronjolson it's been released as 1.4.4. https://pypi.org/project/flask-oidc-ext/

**Pull request merged**
